select fp.PRODUCT_ID, fp.PRODUCT_NAME, fp.PRICE * sum(AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT fp
join FOOD_ORDER fo
on fp.PRODUCT_ID = fo.PRODUCT_ID
where fo.PRODUCE_DATE between '2022-05-01' and '2022-05-31'
group by fp.PRODUCT_ID
order by TOTAL_SALES DESC, fp.PRODUCT_ID