SELECT EXTRACT(HOUR FROM CAST(DATETIME as TIMESTAMP)) as HOUR, count(*) as COUNT
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM CAST(DATETIME as TIMESTAMP)) BETWEEN 9 AND 19
GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
ORDER BY HOUR

-- select EXTRACT(HOUR FROM CAST(DATETIME as TIMESTAMP))
-- from ANIMAL_OUTS
-- where EXTRACT(HOUR FROM CAST(DATETIME as TIMESTAMP)) = 19