# SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
# FROM ITEM_INFO A
# INNER JOIN ITEM_TREE B
# ON A.ITEM_ID = B.ITEM_ID
# WHERE B.PARENT_ITEM_ID IS NOT NULL
# ORDER BY A.ITEM_ID DESC
SELECT B.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B
ON A.ITEM_ID = B.PARENT_ITEM_ID
JOIN ITEM_INFO C
ON B.ITEM_ID = C.ITEM_ID
WHERE A.RARITY = "RARE"
ORDER BY C.ITEM_ID DESC